project:
  type: website
  output-dir: docs

website:
  title: "rediudd"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Sesiones
        menu:
          - href: Sesion1.qmd
            text: Sesi贸n 1
          - href: Sesi贸n 2.qmd
            text: Sesi贸n 2
          - href: Sesion3.qmd
            text: Sesi贸n 3

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

